name: Bug Report
description: File a bug report
labels: bug,unconfirmed

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a report to help us improve!
        
        If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe The Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: additiona-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please copy and paste any relevant log output.
      render: shell
